# Madlibs oyunu
adjective1 = input("Write an adjective: ")
adjective2 = input("Write an adjective: ")
adjective3 = input("Write an adjective: ")
noun1 = input("Write a noun: ")
verb1 = input("Write a verb: ")
print(f"Today I went to a {adjective1} zoo.")
print(f"In an exhibit I saw a {noun1}")
print(f"{noun1} was {adjective2} and {verb1}")
print(f"I was {adjective3}!")